#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <b>jQuery HomeMatic Plugin API</b>"
        echo "Info: <br>Readme: <a href="https://raw.github.com/hobbyquaker/jqhomematic/master/README.md" target="_blank">Lies mich!</a>"
        echo "Name: jqhomematic"
        echo "Version: 1.0"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/www/jqhm
		;;
	*)
        echo "Usage: jqhomematic {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
